---
title: "PeruOECD"
author: "Luisa Olaya"
date: "1/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
set.seed(42) #for consistent results
library(haven)
library(foreign)
library(dplyr)
library(tidyr)
library(ggplot2)
library(stargazer)
library(naniar)

Peru <- read.dta("/Users/lu/Dropbox/Hertie/3/Thesis/R/Peru.dta")
Mexico <- read.csv("/Users/lu/Dropbox/Hertie/3/Thesis/R/prgmexp1.csv")

```

## R Markdown

###Subsetting the data 

```{r cars}



newMexico <- Mexico %>% 
  select("AGE_R", "GENDER_R","B_Q01a", "B_Q01a_T", "B_Q02a", "B_Q02c", "B_Q10c", "B_Q01b", "C_Q01a", "C_Q01c", "C_Q02a", "D_Q03", "D_Q14", "D_Q16a", "D_Q18a_T", "F_Q01b","F_Q02b","F_Q02c","F_Q02d","F_Q02e","F_Q03b","F_Q04a","F_Q04b","F_Q05a","F_Q05b","F_Q07b","G_Q01a","G_Q02a","G_Q02b","G_Q02c","G_Q02d","G_Q03b","G_Q03c","G_Q03d","G_Q03f","G_Q03g","G_Q03h", "G_Q04", "G_Q05a", "G_Q05c", "G_Q05d", "G_Q05e", "G_Q05g", "G_Q05h", "G_Q06", "G_Q07", "G_Q08", "H_Q01a", "H_Q01b", "H_Q01b_T", "H_Q01c", "H_Q01c_T", "H_Q01d", "H_Q01e", "H_Q01e_T", "H_Q01f", "H_Q01g", "H_Q01h", "H_Q02a", "H_Q02b","H_Q02c", "H_Q02d", "H_Q03b", "H_Q03c", "H_Q03d", "H_Q03f", "H_Q03g", "H_Q03h","H_Q04a", "H_Q04b", "H_Q05a", "H_Q05c", "H_Q05d", "H_Q05e", "H_Q05f", "H_Q05g", "H_Q05h", "J_Q03a", "J_Q03b", "J_Q06b", "J_Q07b","COMPUTEREXPERIENCE", "MONTHLYINCPR","YEARLYINCPR", "REG_TL2")

## Missing variables
##Vsualizarion of missing variables


gg_miss_var(newMexico)




table(is.na(newMexico$YEARLYINCPR))
table(is.na(newMexico$MONTHLYINCPR))

table(is.na(newMexico$MONTHLYINCPR))

#droping NAs  


newMexico1 <- drop_na(newMexico, YEARLYINCPR)

# Number of women and men 


barplot(table(newMexico1$GENDER_R))
newMexico1 %>% count(GENDER_R)


newMexico1 %>% count(B_Q01a)
newMexico1 %>% count(B_Q01a_T)
newMexico1 %>% count(B_Q02a)
newMexico1 %>% count(B_Q02c) #x - 3224 V ESTA 1
newMexico1 %>% count(B_Q10c) #x- 3176 V ESTA 2
newMexico1 %>% count(B_Q01b) # 2134 v ESTA 3
newMexico1 %>% count(C_Q01a)
newMexico1 %>% count(C_Q01c) # 3459 v ESTA 4
newMexico1 %>% count(C_Q02a) # 3459 v ESTA 5 
newMexico1 %>% count(D_Q03) # D 42 - r21 
newMexico1 %>% count(D_Q14) #
newMexico1 %>% count(D_Q16a) # V 1008
newMexico1 %>% count(D_Q18a_T) # 13 NA
newMexico1 %>% count(F_Q05a) #
newMexico1 %>% count(F_Q05b)
newMexico1 %>% count(G_Q04)
newMexico1 %>% count(G_Q05a) # 2377 v ESTA 6 
newMexico1 %>% count(G_Q05c) # 2377 v ESTA 7 
newMexico1 %>% count(G_Q05d) # 2377 ESTA 8 
newMexico1 %>% count(G_Q05e) # 2377 ESTA 9 
newMexico1 %>% count(G_Q05g) # 2377 ESTA 10 
newMexico1 %>% count(G_Q05h) # 2377 ESTA 11 
newMexico1 %>% count(G_Q06) # 2377 ESTA 12 
newMexico1 %>% count(G_Q07) # 2377 ESTA 13 
newMexico1 %>% count(G_Q08) # 2377 ESTA 15 
newMexico1 %>% count(H_Q04a) # 1074 V
newMexico1 %>% count(H_Q04b) # 1198 
newMexico1 %>% count(H_Q05a) # 2205 ESTA 16 
newMexico1 %>% count(H_Q05c) # 2205 ESTA 17 
newMexico1 %>% count(H_Q05d) # 2205 ESTA 18 
newMexico1 %>% count(H_Q05e) # 2205 ESTA 19 
newMexico1 %>% count(H_Q05f) # 2205 ESTA 20 
newMexico1 %>% count(H_Q05g) # 2205 ESTA 21 
newMexico1 %>% count(H_Q05h) # 2205 ESTA 22 
newMexico1 %>% count(J_Q03a)
newMexico1 %>% count(J_Q03b) #943
newMexico1 %>% count(J_Q06b) 
newMexico1 %>% count(F_Q01b) #748
newMexico1 %>% count(F_Q02b) 
newMexico1 %>% count(F_Q02c)
newMexico1 %>% count(F_Q02d)
newMexico1 %>% count(F_Q02e)
newMexico1 %>% count(F_Q03b)
newMexico1 %>% count(F_Q04a)
newMexico1 %>% count(F_Q04b)
newMexico1 %>% count(F_Q05a)
newMexico1 %>% count(F_Q05b)
newMexico1 %>% count(G_Q01a)
newMexico1 %>% count(G_Q02a)
newMexico1 %>% count(G_Q02b)
newMexico1 %>% count(G_Q02c)
newMexico1 %>% count(G_Q03b)
newMexico1 %>% count(G_Q03c)
newMexico1 %>% count(G_Q03d)
newMexico1 %>% count(G_Q03f)
newMexico1 %>% count(G_Q03g)
newMexico1 %>% count(G_Q03h)
newMexico1 %>% count(H_Q01a)
newMexico1 %>% count(H_Q01b)
newMexico1 %>% count(H_Q01b_T)
newMexico1 %>% count(H_Q01d)
newMexico1 %>% count(H_Q01c)
newMexico1 %>% count(H_Q01e)
newMexico1 %>% count(H_Q01e_T)
newMexico1 %>% count(H_Q01f)
newMexico1 %>% count(H_Q01g)
newMexico1 %>% count(H_Q01h)
newMexico1 %>% count(H_Q02a)
newMexico1 %>% count(H_Q02b)
newMexico1 %>% count(H_Q02c)
newMexico1 %>% count(H_Q02d)
newMexico1 %>% count(H_Q03b)
newMexico1 %>% count(H_Q03c)
newMexico1 %>% count(H_Q03d)
newMexico1 %>% count(H_Q03f)
newMexico1 %>% count(H_Q03g)
newMexico1 %>% count(H_Q03h)
newMexico1 %>% count(REG_TL2)
newMexico1 %>% count(YEARLYINCPR)



```

##  Merging variables 

You can also embed plots, for example:

```{r warning=FALSE, message=FALSE}

#Gender

newMexico1$GENDER_Rn[newMexico1$GENDER_R == "1"] = 0
newMexico1$GENDER_Rn[newMexico1$GENDER_R == "2"] = 1


#B_Q01a
newMexico1$B_Q01an[newMexico1$B_Q01a == "D"] = NA
newMexico1$B_Q01an[newMexico1$B_Q01a == "1"] = 1
newMexico1$B_Q01an[newMexico1$B_Q01a == "2"] = 2
newMexico1$B_Q01an[newMexico1$B_Q01a == "5"] = 5 
newMexico1$B_Q01an[newMexico1$B_Q01a == "6"] = 6
newMexico1$B_Q01an[newMexico1$B_Q01a == "7"] = 7
newMexico1$B_Q01an[newMexico1$B_Q01a == "11"] = 11
newMexico1$B_Q01an[newMexico1$B_Q01a == "12"] = 12
newMexico1$B_Q01an[newMexico1$B_Q01a == "13"] = 13
newMexico1$B_Q01an[newMexico1$B_Q01a == "14"] = 14
newMexico1$B_Q01an[newMexico1$B_Q01a == "15"] = 15

#B_Q01a_T

newMexico1$B_Q01a_Tn[newMexico1$B_Q01a_T == "M"] = NA
newMexico1$B_Q01a_Tn[newMexico1$B_Q01a_T == "1"] = 1
newMexico1$B_Q01a_Tn[newMexico1$B_Q01a_T == "2"] = 2
newMexico1$B_Q01a_Tn[newMexico1$B_Q01a_T == "3"] = 3 
newMexico1$B_Q01a_Tn[newMexico1$B_Q01a_T == "4"] = 4

#B_Q02a

newMexico1$B_Q02an[newMexico1$B_Q02a == "R"] = NA
newMexico1$B_Q02an[newMexico1$B_Q02a == "1"] = 0
newMexico1$B_Q02an[newMexico1$B_Q02a== "2"] = 1

#B_Q02c
newMexico1$B_Q02cn[newMexico1$B_Q02c == "V"] = NA
newMexico1$B_Q02cn[newMexico1$B_Q02c == "1"] = 1
newMexico1$B_Q02cn[newMexico1$B_Q02c == "2"] = 2
newMexico1$B_Q02cn[newMexico1$B_Q02c == "3"] = 3
newMexico1$B_Q02cn[newMexico1$B_Q02c == "4"] = 4
newMexico1$B_Q02cn[newMexico1$B_Q02c == "5"] = 5
newMexico1$B_Q02cn[newMexico1$B_Q02c == "6"] = 6
newMexico1$B_Q02cn[newMexico1$B_Q02c == "7"] = 7
newMexico1$B_Q02cn[newMexico1$B_Q02c == "8"] = 8
newMexico1$B_Q02cn[newMexico1$B_Q02c == "9"] = 9 
newMexico1$B_Q02cn[newMexico1$B_Q02c == "R"] = NA

#B_Q10c

newMexico1$B_Q10cn[newMexico1$B_Q10c == "V"] = NA
newMexico1$B_Q10cn[newMexico1$B_Q10c == "1"] = 1
newMexico1$B_Q10cn[newMexico1$B_Q10c == "2"] = 2
newMexico1$B_Q10cn[newMexico1$B_Q10c == "3"] = 3
newMexico1$B_Q10cn[newMexico1$B_Q10c == "4"] = 4

#B_Q01b

newMexico1$B_Q01bn[newMexico1$B_Q01b == "V"] = NA
newMexico1$B_Q01bn[newMexico1$B_Q01b == "D"] = NA
newMexico1$B_Q01bn[newMexico1$B_Q01b == "R"] = NA
newMexico1$B_Q01bn[newMexico1$B_Q01b == "1"] = 1
newMexico1$B_Q01bn[newMexico1$B_Q01b == "2"] = 2
newMexico1$B_Q01bn[newMexico1$B_Q01b == "3"] = 3
newMexico1$B_Q01bn[newMexico1$B_Q01b == "4"] = 4
newMexico1$B_Q01bn[newMexico1$B_Q01b == "5"] = 5
newMexico1$B_Q01bn[newMexico1$B_Q01b == "6"] = 6
newMexico1$B_Q01bn[newMexico1$B_Q01b == "7"] = 7
newMexico1$B_Q01bn[newMexico1$B_Q01b == "8"] = 8
newMexico1$B_Q01bn[newMexico1$B_Q01b == "9"] = 9

# C_Q01c
newMexico1$C_Q01cn[newMexico1$C_Q01c == "V"] = NA

#C_Q02a

newMexico1$C_Q02an[newMexico1$C_Q02a == "V"] = NA

#D_Q03

newMexico1$D_Q03n[newMexico1$D_Q03 == "R"] = NA
newMexico1$D_Q03n[newMexico1$D_Q03 == "D"] = NA
newMexico1$D_Q03n[newMexico1$D_Q03 == "1"] = 1
newMexico1$D_Q03n[newMexico1$D_Q03 == "2"] = 2
newMexico1$D_Q03n[newMexico1$D_Q03 == "3"] = 3

#D_Q14

newMexico1$D_Q14n[newMexico1$D_Q14 == "D"] = NA
newMexico1$D_Q14n[newMexico1$D_Q14 == "1"] = 1
newMexico1$D_Q14n[newMexico1$D_Q14 == "2"] = 2
newMexico1$D_Q14n[newMexico1$D_Q14 == "3"] = 3
newMexico1$D_Q14n[newMexico1$D_Q14 == "4"] = 4
newMexico1$D_Q14n[newMexico1$D_Q14 == "5"] = 5

#D_Q16a

newMexico1$D_Q16an[newMexico1$D_Q16a == "V"] = NA
newMexico1$D_Q16an[newMexico1$D_Q16a == "1"] = 1
newMexico1$D_Q16an[newMexico1$D_Q16a == "2"] = 2
newMexico1$D_Q16an[newMexico1$D_Q16a == "3"] = 3
newMexico1$D_Q16an[newMexico1$D_Q16a == "4"] = 4
newMexico1$D_Q16an[newMexico1$D_Q16a == "5"] = 5
newMexico1$D_Q16an[newMexico1$D_Q16a == "6"] = 6
newMexico1$D_Q16an[newMexico1$D_Q16a == "7"] = 7

#F_Q01b

newMexico1$F_Q01bn[newMexico1$F_Q01b== "1"] = 1
newMexico1$F_Q01bn[newMexico1$F_Q01b== "2"] = 2
newMexico1$F_Q01bn[newMexico1$F_Q01b== "3"] = 3
newMexico1$F_Q01bn[newMexico1$F_Q01b== "4"] = 4
newMexico1$F_Q01bn[newMexico1$F_Q01b== "5"] = 5
newMexico1$F_Q01bn[newMexico1$F_Q01b== "N"] = NA
newMexico1$F_Q01bn[newMexico1$F_Q01b== "R"] = NA
newMexico1$F_Q01bn[newMexico1$F_Q01b== "V"] = NA

#F_Q02b

newMexico1$F_Q02bn[newMexico1$F_Q02b== "1"] = 1
newMexico1$F_Q02bn[newMexico1$F_Q02b== "2"] = 2
newMexico1$F_Q02bn[newMexico1$F_Q02b== "3"] = 3
newMexico1$F_Q02bn[newMexico1$F_Q02b== "4"] = 4
newMexico1$F_Q02bn[newMexico1$F_Q02b== "5"] = 5
newMexico1$F_Q02bn[newMexico1$F_Q02b== "N"] = NA
newMexico1$F_Q02bn[newMexico1$F_Q02b== "R"] = NA

#F_Q02c

newMexico1$F_Q02cn[newMexico1$F_Q02c== "1"] = 1
newMexico1$F_Q02cn[newMexico1$F_Q02c== "2"] = 2
newMexico1$F_Q02cn[newMexico1$F_Q02c== "3"] = 3
newMexico1$F_Q02cn[newMexico1$F_Q02c== "4"] = 4
newMexico1$F_Q02cn[newMexico1$F_Q02c== "5"] = 5
newMexico1$F_Q02cn[newMexico1$F_Q02c== "N"] = NA
newMexico1$F_Q02cn[newMexico1$F_Q02c== "R"] = NA

#F_Q02d

newMexico1$F_Q02dn[newMexico1$F_Q02d== "1"] = 1
newMexico1$F_Q02dn[newMexico1$F_Q02d== "2"] = 2
newMexico1$F_Q02dn[newMexico1$F_Q02d== "3"] = 3
newMexico1$F_Q02dn[newMexico1$F_Q02d== "4"] = 4
newMexico1$F_Q02dn[newMexico1$F_Q02d== "5"] = 5
newMexico1$F_Q02dn[newMexico1$F_Q02d== "D"] = NA
newMexico1$F_Q02dn[newMexico1$F_Q02d== "N"] = NA 
newMexico1$F_Q02dn[newMexico1$F_Q02d== "R"] = NA

#F_Q02e

newMexico1$F_Q02en[newMexico1$F_Q02e== "1"] = 1
newMexico1$F_Q02en[newMexico1$F_Q02e== "2"] = 2
newMexico1$F_Q02en[newMexico1$F_Q02e== "3"] = 3
newMexico1$F_Q02en[newMexico1$F_Q02e== "4"] = 4
newMexico1$F_Q02en[newMexico1$F_Q02e== "5"] = 5
newMexico1$F_Q02en[newMexico1$F_Q02e== "N"] = NA 
newMexico1$F_Q02en[newMexico1$F_Q02e== "R"] = NA

#F_Q03b

newMexico1$F_Q03bn[newMexico1$F_Q03b== "1"] = 1
newMexico1$F_Q03bn[newMexico1$F_Q03b== "2"] = 2
newMexico1$F_Q03bn[newMexico1$F_Q03b== "3"] = 3
newMexico1$F_Q03bn[newMexico1$F_Q03b== "4"] = 4
newMexico1$F_Q03bn[newMexico1$F_Q03b== "5"] = 5
newMexico1$F_Q03bn[newMexico1$F_Q03b== "D"] = NA
newMexico1$F_Q03bn[newMexico1$F_Q03b== "N"] = NA

#F_Q04a

newMexico1$F_Q04an[newMexico1$F_Q04a== "1"] = 1
newMexico1$F_Q04an[newMexico1$F_Q04a== "2"] = 2
newMexico1$F_Q04an[newMexico1$F_Q04a== "3"] = 3
newMexico1$F_Q04an[newMexico1$F_Q04a== "4"] = 4
newMexico1$F_Q04an[newMexico1$F_Q04a== "5"] = 5
newMexico1$F_Q04an[newMexico1$F_Q04a== "D"] = NA
newMexico1$F_Q04an[newMexico1$F_Q04a== "N"] = NA

#F_Q04b

newMexico1$F_Q04bn[newMexico1$F_Q04b== "1"] = 1
newMexico1$F_Q04bn[newMexico1$F_Q04b== "2"] = 2
newMexico1$F_Q04bn[newMexico1$F_Q04b== "3"] = 3
newMexico1$F_Q04bn[newMexico1$F_Q04b== "4"] = 4
newMexico1$F_Q04bn[newMexico1$F_Q04b== "5"] = 5
newMexico1$F_Q04bn[newMexico1$F_Q04b== "N"] = NA

#F_Q05a

newMexico1$F_Q05an[newMexico1$F_Q05a == "D"] = NA
newMexico1$F_Q05an[newMexico1$F_Q05a == "N"] = NA
newMexico1$F_Q05an[newMexico1$F_Q05a == "1"] = 1
newMexico1$F_Q05an[newMexico1$F_Q05a == "2"] = 2
newMexico1$F_Q05an[newMexico1$F_Q05a == "3"] = 3
newMexico1$F_Q05an[newMexico1$F_Q05a == "4"] = 4
newMexico1$F_Q05an[newMexico1$F_Q05a == "5"] = 5

#F_Q05b

newMexico1$F_Q05bn[newMexico1$F_Q05b == "D"] = NA
newMexico1$F_Q05bn[newMexico1$F_Q05b == "N"] = NA
newMexico1$F_Q05bn[newMexico1$F_Q05b == "1"] = 1
newMexico1$F_Q05bn[newMexico1$F_Q05b == "2"] = 2
newMexico1$F_Q05bn[newMexico1$F_Q05b == "3"] = 3
newMexico1$F_Q05bn[newMexico1$F_Q05b == "4"] = 4
newMexico1$F_Q05bn[newMexico1$F_Q05b == "5"] = 5

#F_Q07b

newMexico1$F_Q07bn[newMexico1$F_Q07b == "D"] = NA
newMexico1$F_Q07bn[newMexico1$F_Q07b == "N"] = NA
newMexico1$F_Q07bn[newMexico1$F_Q07b == "1"] = 0
newMexico1$F_Q07bn[newMexico1$F_Q07b == "2"] = 1

# G_Q01a

newMexico1$G_Q01an[newMexico1$G_Q01a == "N"] = NA
newMexico1$G_Q01an[newMexico1$G_Q01a == "1"] = 1
newMexico1$G_Q01an[newMexico1$G_Q01a == "2"] = 2
newMexico1$G_Q01an[newMexico1$G_Q01a == "3"] = 3
newMexico1$G_Q01an[newMexico1$G_Q01a == "4"] = 4
newMexico1$G_Q01an[newMexico1$G_Q01a == "5"] = 5

# G_Q02a

newMexico1$G_Q02an[newMexico1$G_Q02a == "N"] = NA
newMexico1$G_Q02an[newMexico1$G_Q02a == "1"] = 1
newMexico1$G_Q02an[newMexico1$G_Q02a == "2"] = 2
newMexico1$G_Q02an[newMexico1$G_Q02a == "3"] = 3
newMexico1$G_Q02an[newMexico1$G_Q02a == "4"] = 4
newMexico1$G_Q02an[newMexico1$G_Q02a == "5"] = 5

# G_Q02b

newMexico1$G_Q02bn[newMexico1$G_Q02b== "1"] = 1
newMexico1$G_Q02bn[newMexico1$G_Q02b== "2"] = 2
newMexico1$G_Q02bn[newMexico1$G_Q02b== "3"] = 3
newMexico1$G_Q02bn[newMexico1$G_Q02b== "4"] = 4
newMexico1$G_Q02bn[newMexico1$G_Q02b== "5"] = 5
newMexico1$G_Q02bn[newMexico1$G_Q02b== "N"] = NA

# G_Q02c

newMexico1$G_Q02cn[newMexico1$G_Q02c == "N"] = NA
newMexico1$G_Q02cn[newMexico1$G_Q02c == "1"] = 1
newMexico1$G_Q02cn[newMexico1$G_Q02c == "2"] = 2
newMexico1$G_Q02cn[newMexico1$G_Q02c == "3"] = 3
newMexico1$G_Q02cn[newMexico1$G_Q02c == "4"] = 4
newMexico1$G_Q02cn[newMexico1$G_Q02c == "5"] = 5

# G_Q02d

newMexico1$G_Q02dn[newMexico1$G_Q02d == "N"] = NA
newMexico1$G_Q02dn[newMexico1$G_Q02d == "1"] = 1
newMexico1$G_Q02dn[newMexico1$G_Q02d == "2"] = 2
newMexico1$G_Q02dn[newMexico1$G_Q02d == "3"] = 3
newMexico1$G_Q02dn[newMexico1$G_Q02d == "4"] = 4
newMexico1$G_Q02dn[newMexico1$G_Q02d == "5"] = 5

# G_Q03b

newMexico1$G_Q03bn[newMexico1$G_Q03b == "D"] = NA
newMexico1$G_Q03bn[newMexico1$G_Q03b == "N"] = NA
newMexico1$G_Q03bn[newMexico1$G_Q03b == "1"] = 1
newMexico1$G_Q03bn[newMexico1$G_Q03b == "2"] = 2
newMexico1$G_Q03bn[newMexico1$G_Q03b == "3"] = 3
newMexico1$G_Q03bn[newMexico1$G_Q03b == "4"] = 4
newMexico1$G_Q03bn[newMexico1$G_Q03b == "5"] = 5

# G_Q03c

newMexico1$G_Q03cn[newMexico1$G_Q03c == "N"] = NA
newMexico1$G_Q03cn[newMexico1$G_Q03c == "1"] = 1
newMexico1$G_Q03cn[newMexico1$G_Q03c == "2"] = 2
newMexico1$G_Q03cn[newMexico1$G_Q03c == "3"] = 3
newMexico1$G_Q03cn[newMexico1$G_Q03c == "4"] = 4
newMexico1$G_Q03cn[newMexico1$G_Q03c == "5"] = 5

# G_Q03d

newMexico1$G_Q03dn[newMexico1$G_Q03d == "N"] = NA
newMexico1$G_Q03dn[newMexico1$G_Q03d == "1"] = 1
newMexico1$G_Q03dn[newMexico1$G_Q03d == "2"] = 2
newMexico1$G_Q03dn[newMexico1$G_Q03d == "3"] = 3
newMexico1$G_Q03dn[newMexico1$G_Q03d == "4"] = 4
newMexico1$G_Q03dn[newMexico1$G_Q03d == "5"] = 5

# G_Q03f

newMexico1$G_Q03fn[newMexico1$G_Q03f == "N"] = NA
newMexico1$G_Q03fn[newMexico1$G_Q03f == "1"] = 1
newMexico1$G_Q03fn[newMexico1$G_Q03f == "2"] = 2
newMexico1$G_Q03fn[newMexico1$G_Q03f == "3"] = 3
newMexico1$G_Q03fn[newMexico1$G_Q03f == "4"] = 4
newMexico1$G_Q03fn[newMexico1$G_Q03f == "5"] = 5

# G_Q03g

newMexico1$G_Q03gn[newMexico1$G_Q03g == "N"] = NA
newMexico1$G_Q03gn[newMexico1$G_Q03g == "1"] = 1
newMexico1$G_Q03gn[newMexico1$G_Q03g == "2"] = 2
newMexico1$G_Q03gn[newMexico1$G_Q03g == "3"] = 3
newMexico1$G_Q03gn[newMexico1$G_Q03g == "4"] = 4
newMexico1$G_Q03gn[newMexico1$G_Q03g == "5"] = 5

# G_Q03h

newMexico1$G_Q03hn[newMexico1$G_Q03h == "N"] = NA
newMexico1$G_Q03hn[newMexico1$G_Q03h == "1"] = 1
newMexico1$G_Q03hn[newMexico1$G_Q03h == "2"] = 2
newMexico1$G_Q03hn[newMexico1$G_Q03h == "3"] = 3
newMexico1$G_Q03hn[newMexico1$G_Q03h == "4"] = 4
newMexico1$G_Q03hn[newMexico1$G_Q03h == "5"] = 5

# G_Q04

newMexico1$G_Q04n[newMexico1$G_Q04 == "N"] = NA
newMexico1$G_Q04n[newMexico1$G_Q04 == "1"] = 0
newMexico1$G_Q04n[newMexico1$G_Q04 == "2"] = 1

# G_Q05a

newMexico1$G_Q05an[newMexico1$G_Q05a == "V"] = NA
newMexico1$G_Q05an[newMexico1$G_Q05a == "N"] = NA
newMexico1$G_Q05an[newMexico1$G_Q05a == "1"] = 1
newMexico1$G_Q05an[newMexico1$G_Q05a == "2"] = 2
newMexico1$G_Q05an[newMexico1$G_Q05a == "3"] = 3
newMexico1$G_Q05an[newMexico1$G_Q05a == "4"] = 4
newMexico1$G_Q05an[newMexico1$G_Q05a == "5"] = 5

# G_Q05c

newMexico1$G_Q05cn[newMexico1$G_Q05c == "V"] = NA
newMexico1$G_Q05cn[newMexico1$G_Q05c == "N"] = NA
newMexico1$G_Q05cn[newMexico1$G_Q05c == "1"] = 1
newMexico1$G_Q05cn[newMexico1$G_Q05c == "2"] = 2
newMexico1$G_Q05cn[newMexico1$G_Q05c == "3"] = 3
newMexico1$G_Q05cn[newMexico1$G_Q05c == "4"] = 4
newMexico1$G_Q05cn[newMexico1$G_Q05c == "5"] = 5

#G_Q05d 
newMexico1$G_Q05dn[newMexico1$G_Q05d == "V"] = NA
newMexico1$G_Q05dn[newMexico1$G_Q05d == "N"] = NA
newMexico1$G_Q05dn[newMexico1$G_Q05d == "1"] = 1
newMexico1$G_Q05dn[newMexico1$G_Q05d == "2"] = 2
newMexico1$G_Q05dn[newMexico1$G_Q05d == "3"] = 3
newMexico1$G_Q05dn[newMexico1$G_Q05d == "4"] = 4
newMexico1$G_Q05dn[newMexico1$G_Q05d == "5"] = 5

#G_Q05e

newMexico1$G_Q05en[newMexico1$G_Q05e == "V"] = NA
newMexico1$G_Q05en[newMexico1$G_Q05e == "N"] = NA
newMexico1$G_Q05en[newMexico1$G_Q05e == "1"] = 1
newMexico1$G_Q05en[newMexico1$G_Q05e == "2"] = 2
newMexico1$G_Q05en[newMexico1$G_Q05e == "3"] = 3
newMexico1$G_Q05en[newMexico1$G_Q05e == "4"] = 4
newMexico1$G_Q05en[newMexico1$G_Q05e == "5"] = 5

#G_Q05g 

newMexico1$G_Q05gn[newMexico1$G_Q05g == "V"] = NA
newMexico1$G_Q05gn[newMexico1$G_Q05g == "N"] = NA
newMexico1$G_Q05gn[newMexico1$G_Q05g == "1"] = 1
newMexico1$G_Q05gn[newMexico1$G_Q05g == "2"] = 2
newMexico1$G_Q05gn[newMexico1$G_Q05g == "3"] = 3
newMexico1$G_Q05gn[newMexico1$G_Q05g == "4"] = 4
newMexico1$G_Q05gn[newMexico1$G_Q05g == "5"] = 5

#G_Q05h

newMexico1$G_Q05hn[newMexico1$G_Q05h == "V"] =NA
newMexico1$G_Q05hn[newMexico1$G_Q05h == "N"] =NA
newMexico1$G_Q05hn[newMexico1$G_Q05h == "1"] =1
newMexico1$G_Q05hn[newMexico1$G_Q05h == "2"] =2
newMexico1$G_Q05hn[newMexico1$G_Q05h == "3"] =3
newMexico1$G_Q05hn[newMexico1$G_Q05h == "4"] =4
newMexico1$G_Q05hn[newMexico1$G_Q05h == "5"] =5


#G_Q06

newMexico1$G_Q06n[newMexico1$G_Q06 == "V"] =NA
newMexico1$G_Q06n[newMexico1$G_Q06 == "N"] =NA
newMexico1$G_Q06n[newMexico1$G_Q06 == "R"] =NA
newMexico1$G_Q06n[newMexico1$G_Q06 == "1"] =1
newMexico1$G_Q06n[newMexico1$G_Q06 == "2"] =2
newMexico1$G_Q06n[newMexico1$G_Q06 == "3"] =3
newMexico1$G_Q06n[newMexico1$G_Q06 == "4"] =4
newMexico1$G_Q06n[newMexico1$G_Q06 == "5"] =5

#G_Q07

newMexico1$G_Q07n[newMexico1$G_Q07 == "V"] =NA
newMexico1$G_Q07n[newMexico1$G_Q07 == "N"] =NA
newMexico1$G_Q07n[newMexico1$G_Q07 == "1"] =0
newMexico1$G_Q07n[newMexico1$G_Q07 == "2"] =1

#G_Q08 

newMexico1$G_Q08n[newMexico1$G_Q08 == "V"] =NA
newMexico1$G_Q08n[newMexico1$G_Q08 == "N"] =NA
newMexico1$G_Q08n[newMexico1$G_Q08 == "D"] =NA
newMexico1$G_Q08n[newMexico1$G_Q08 == "R"] =NA
newMexico1$G_Q08n[newMexico1$G_Q08 == "1"] =0
newMexico1$G_Q08n[newMexico1$G_Q08 == "2"] =1

#H_q01a

newMexico1$H_Q01an[newMexico1$H_Q01a == "N"] =NA
newMexico1$H_Q01an[newMexico1$H_Q01a == "1"] =1
newMexico1$H_Q01an[newMexico1$H_Q01a == "2"] =2
newMexico1$H_Q01an[newMexico1$H_Q01a == "3"] =3
newMexico1$H_Q01an[newMexico1$H_Q01a == "4"] =4
newMexico1$H_Q01an[newMexico1$H_Q01a == "5"] =5

#H_q01b

newMexico1$H_Q01bn[newMexico1$H_Q01b == "N"] =NA
newMexico1$H_Q01bn[newMexico1$H_Q01b == "1"] =1
newMexico1$H_Q01bn[newMexico1$H_Q01b == "2"] =2
newMexico1$H_Q01bn[newMexico1$H_Q01b == "3"] =3
newMexico1$H_Q01bn[newMexico1$H_Q01b == "4"] =4
newMexico1$H_Q01bn[newMexico1$H_Q01b == "5"] =5

#H_q01b_T

newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "N"] =NA
newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "1"] =1
newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "2"] =2
newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "3"] =3
newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "4"] =4
newMexico1$H_Q01b_Tn[newMexico1$H_Q01b_T == "5"] =5

#H_q01c

newMexico1$H_Q01cn[newMexico1$H_Q01c == "N"] =NA
newMexico1$H_Q01cn[newMexico1$H_Q01c == "1"] =1
newMexico1$H_Q01cn[newMexico1$H_Q01c == "2"] =2
newMexico1$H_Q01cn[newMexico1$H_Q01c == "3"] =3
newMexico1$H_Q01cn[newMexico1$H_Q01c == "4"] =4
newMexico1$H_Q01cn[newMexico1$H_Q01c == "5"] =5

#H_q01c_T

newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "N"] =NA
newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "1"] =1
newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "2"] =2
newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "3"] =3
newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "4"] =4
newMexico1$H_Q01c_Tn[newMexico1$H_Q01c_T == "5"] =5

#H_q01d

newMexico1$H_Q01dn[newMexico1$H_Q01d == "N"] =NA
newMexico1$H_Q01dn[newMexico1$H_Q01d == "1"] =1
newMexico1$H_Q01dn[newMexico1$H_Q01d == "2"] =2
newMexico1$H_Q01dn[newMexico1$H_Q01d == "3"] =3
newMexico1$H_Q01dn[newMexico1$H_Q01d == "4"] =4
newMexico1$H_Q01dn[newMexico1$H_Q01d == "5"] =5

#H_q01e

newMexico1$H_Q01en[newMexico1$H_Q01e == "N"] =NA
newMexico1$H_Q01en[newMexico1$H_Q01e == "R"] =NA
newMexico1$H_Q01en[newMexico1$H_Q01e == "1"] =1
newMexico1$H_Q01en[newMexico1$H_Q01e == "2"] =2
newMexico1$H_Q01en[newMexico1$H_Q01e == "3"] =3
newMexico1$H_Q01en[newMexico1$H_Q01e == "4"] =4
newMexico1$H_Q01en[newMexico1$H_Q01e == "5"] =5

#H_q01e_T

newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "N"] =NA
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "R"] =NA
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "1"] =1
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "2"] =2
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "3"] =3
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "4"] =4
newMexico1$H_Q01e_Tn[newMexico1$H_Q01e_T == "5"] =5

#H_q01f

newMexico1$H_Q01fn[newMexico1$H_Q01f == "N"] =NA
newMexico1$H_Q01fn[newMexico1$H_Q01f == "R"] =NA
newMexico1$H_Q01fn[newMexico1$H_Q01f == "1"] =1
newMexico1$H_Q01fn[newMexico1$H_Q01f == "2"] =2
newMexico1$H_Q01fn[newMexico1$H_Q01f == "3"] =3
newMexico1$H_Q01fn[newMexico1$H_Q01f == "4"] =4
newMexico1$H_Q01fn[newMexico1$H_Q01f == "5"] =5

#H_q01g

newMexico1$H_Q01gn[newMexico1$H_Q01g == "N"] =NA
newMexico1$H_Q01gn[newMexico1$H_Q01g == "1"] =1
newMexico1$H_Q01gn[newMexico1$H_Q01g == "2"] =2
newMexico1$H_Q01gn[newMexico1$H_Q01g == "3"] =3
newMexico1$H_Q01gn[newMexico1$H_Q01g == "4"] =4
newMexico1$H_Q01gn[newMexico1$H_Q01g == "5"] =5

#H_q01h 

newMexico1$H_Q01hn[newMexico1$H_Q01h== "1"] = 1
newMexico1$H_Q01hn[newMexico1$H_Q01h== "2"] = 2
newMexico1$H_Q01hn[newMexico1$H_Q01h== "3"] = 3
newMexico1$H_Q01hn[newMexico1$H_Q01h== "4"] = 4
newMexico1$H_Q01hn[newMexico1$H_Q01h== "5"] = 5
newMexico1$H_Q01hn[newMexico1$H_Q01h== "N"] = NA

#H_q02a

newMexico1$H_Q02an[newMexico1$H_Q02a== "1"] = 1
newMexico1$H_Q02an[newMexico1$H_Q02a== "2"] = 2
newMexico1$H_Q02an[newMexico1$H_Q02a== "3"] = 3
newMexico1$H_Q02an[newMexico1$H_Q02a== "4"] = 4
newMexico1$H_Q02an[newMexico1$H_Q02a== "5"] = 5
newMexico1$H_Q02an[newMexico1$H_Q02a== "N"] = NA

#H_q02b

newMexico1$H_Q02bn[newMexico1$H_Q02b== "1"] = 1
newMexico1$H_Q02bn[newMexico1$H_Q02b== "2"] = 2
newMexico1$H_Q02bn[newMexico1$H_Q02b== "3"] = 3
newMexico1$H_Q02bn[newMexico1$H_Q02b== "4"] = 4
newMexico1$H_Q02bn[newMexico1$H_Q02b== "5"] = 5
newMexico1$H_Q02bn[newMexico1$H_Q02b== "N"] = NA

#H_q02c

newMexico1$H_Q02cn[newMexico1$H_Q02c== "1"] = 1
newMexico1$H_Q02cn[newMexico1$H_Q02c== "2"] = 2
newMexico1$H_Q02cn[newMexico1$H_Q02c== "3"] = 3
newMexico1$H_Q02cn[newMexico1$H_Q02c== "4"] = 4
newMexico1$H_Q02cn[newMexico1$H_Q02c== "5"] = 5
newMexico1$H_Q02cn[newMexico1$H_Q02c== "N"] = NA

#H_q02d

newMexico1$H_Q02dn[newMexico1$H_Q02d== "1"] = 1
newMexico1$H_Q02dn[newMexico1$H_Q02d== "2"] = 2
newMexico1$H_Q02dn[newMexico1$H_Q02d== "3"] = 3
newMexico1$H_Q02dn[newMexico1$H_Q02d== "4"] = 4
newMexico1$H_Q02dn[newMexico1$H_Q02d== "5"] = 5
newMexico1$H_Q02dn[newMexico1$H_Q02d== "N"] = NA

#H_q03b

newMexico1$H_Q03bn[newMexico1$H_Q03b== "1"] = 1
newMexico1$H_Q03bn[newMexico1$H_Q03b== "2"] = 2
newMexico1$H_Q03bn[newMexico1$H_Q03b== "3"] = 3
newMexico1$H_Q03bn[newMexico1$H_Q03b== "4"] = 4
newMexico1$H_Q03bn[newMexico1$H_Q03b== "5"] = 5
newMexico1$H_Q03bn[newMexico1$H_Q03b== "N"] = NA

#H_q03c

newMexico1$H_Q03cn[newMexico1$H_Q03c== "1"] = 1
newMexico1$H_Q03cn[newMexico1$H_Q03c== "2"] = 2
newMexico1$H_Q03cn[newMexico1$H_Q03c== "3"] = 3
newMexico1$H_Q03cn[newMexico1$H_Q03c== "4"] = 4
newMexico1$H_Q03cn[newMexico1$H_Q03c== "5"] = 5
newMexico1$H_Q03cn[newMexico1$H_Q03c== "D"] = NA
newMexico1$H_Q03cn[newMexico1$H_Q03c== "N"] = NA

#H_q03d

newMexico1$H_Q03dn[newMexico1$H_Q03d== "1"] = 1
newMexico1$H_Q03dn[newMexico1$H_Q03d== "2"] = 2
newMexico1$H_Q03dn[newMexico1$H_Q03d== "3"] = 3
newMexico1$H_Q03dn[newMexico1$H_Q03d== "4"] = 4
newMexico1$H_Q03dn[newMexico1$H_Q03d== "5"] = 5
newMexico1$H_Q03dn[newMexico1$H_Q03d== "N"] = NA

#H_q03f

newMexico1$H_Q03fn[newMexico1$H_Q03f== "1"] = 1
newMexico1$H_Q03fn[newMexico1$H_Q03f== "2"] = 2
newMexico1$H_Q03fn[newMexico1$H_Q03f== "3"] = 3
newMexico1$H_Q03fn[newMexico1$H_Q03f== "4"] = 4
newMexico1$H_Q03fn[newMexico1$H_Q03f== "5"] = 5
newMexico1$H_Q03fn[newMexico1$H_Q03f== "N"] = NA

#H_q03g

newMexico1$H_Q03gn[newMexico1$H_Q03g== "1"] = 1
newMexico1$H_Q03gn[newMexico1$H_Q03g== "2"] = 2
newMexico1$H_Q03gn[newMexico1$H_Q03g== "3"] = 3
newMexico1$H_Q03gn[newMexico1$H_Q03g== "4"] = 4
newMexico1$H_Q03gn[newMexico1$H_Q03g== "5"] = 5
newMexico1$H_Q03gn[newMexico1$H_Q03g== "N"] = NA

#H_q03h

newMexico1$H_Q03hn[newMexico1$H_Q03h== "1"] = 1
newMexico1$H_Q03hn[newMexico1$H_Q03h== "2"] = 2
newMexico1$H_Q03hn[newMexico1$H_Q03h== "3"] = 3
newMexico1$H_Q03hn[newMexico1$H_Q03h== "4"] = 4
newMexico1$H_Q03hn[newMexico1$H_Q03h== "5"] = 5
newMexico1$H_Q03hn[newMexico1$H_Q03h== "N"] = NA

#H_Q04a

newMexico1$H_Q04an[newMexico1$H_Q04a == "V"] =NA
newMexico1$H_Q04an[newMexico1$H_Q04a == "N"] =NA
newMexico1$H_Q04an[newMexico1$H_Q04a == "1"] =0
newMexico1$H_Q04an[newMexico1$H_Q04a == "2"] =1

#H_Q04b

newMexico1$H_Q04bn[newMexico1$H_Q04b == "V"] =NA
newMexico1$H_Q04bn[newMexico1$H_Q04b == "N"] =NA
newMexico1$H_Q04bn[newMexico1$H_Q04b == "1"] =0
newMexico1$H_Q04bn[newMexico1$H_Q04b == "2"] =1

#H_Q05a

newMexico1$H_Q05an[newMexico1$H_Q05a == "V"] =NA
newMexico1$H_Q05an[newMexico1$H_Q05a == "N"] =NA
newMexico1$H_Q05an[newMexico1$H_Q05a == "1"] =1
newMexico1$H_Q05an[newMexico1$H_Q05a == "2"] =2
newMexico1$H_Q05an[newMexico1$H_Q05a == "3"] =3
newMexico1$H_Q05an[newMexico1$H_Q05a == "4"] =4
newMexico1$H_Q05an[newMexico1$H_Q05a == "5"] =5

#H_Q05c

newMexico1$H_Q05cn[newMexico1$H_Q05c == "V"] =NA
newMexico1$H_Q05cn[newMexico1$H_Q05c == "N"] =NA
newMexico1$H_Q05cn[newMexico1$H_Q05c == "1"] =1
newMexico1$H_Q05cn[newMexico1$H_Q05c == "2"] =2
newMexico1$H_Q05cn[newMexico1$H_Q05c == "3"] =3
newMexico1$H_Q05cn[newMexico1$H_Q05c == "4"] =4
newMexico1$H_Q05cn[newMexico1$H_Q05c == "5"] =5

#H_Q05d

newMexico1$H_Q05dn[newMexico1$H_Q05d == "V"] =NA
newMexico1$H_Q05dn[newMexico1$H_Q05d == "N"] =NA
newMexico1$H_Q05dn[newMexico1$H_Q05d == "1"] =1
newMexico1$H_Q05dn[newMexico1$H_Q05d == "2"] =2
newMexico1$H_Q05dn[newMexico1$H_Q05d == "3"] =3
newMexico1$H_Q05dn[newMexico1$H_Q05d == "4"] =4
newMexico1$H_Q05dn[newMexico1$H_Q05d == "5"] =5

#H_Q05e

newMexico1$H_Q05en[newMexico1$H_Q05e == "V"] =NA
newMexico1$H_Q05en[newMexico1$H_Q05e == "N"] =NA
newMexico1$H_Q05en[newMexico1$H_Q05e == "1"] =1
newMexico1$H_Q05en[newMexico1$H_Q05e == "2"] =2
newMexico1$H_Q05en[newMexico1$H_Q05e == "3"] =3
newMexico1$H_Q05en[newMexico1$H_Q05e == "4"] =4
newMexico1$H_Q05en[newMexico1$H_Q05e == "5"] =5

#H_Q05f

newMexico1$H_Q05fn[newMexico1$H_Q05f == "V"] =NA
newMexico1$H_Q05fn[newMexico1$H_Q05f == "N"] =NA
newMexico1$H_Q05fn[newMexico1$H_Q05f == "1"] =1
newMexico1$H_Q05fn[newMexico1$H_Q05f == "2"] =2
newMexico1$H_Q05fn[newMexico1$H_Q05f == "3"] =3
newMexico1$H_Q05fn[newMexico1$H_Q05f == "4"] =4
newMexico1$H_Q05fn[newMexico1$H_Q05f == "5"] =5

#H_Q05g

newMexico1$H_Q05gn[newMexico1$H_Q05g == "V"] =NA
newMexico1$H_Q05gn[newMexico1$H_Q05g == "N"] =NA
newMexico1$H_Q05gn[newMexico1$H_Q05g == "1"] =1
newMexico1$H_Q05gn[newMexico1$H_Q05g == "2"] =2
newMexico1$H_Q05gn[newMexico1$H_Q05g == "3"] =3
newMexico1$H_Q05gn[newMexico1$H_Q05g == "4"] =4
newMexico1$H_Q05gn[newMexico1$H_Q05g == "5"] =5

#H_Q05h

newMexico1$H_Q05hn[newMexico1$H_Q05h == "V"] =NA
newMexico1$H_Q05hn[newMexico1$H_Q05h == "N"] =NA
newMexico1$H_Q05hn[newMexico1$H_Q05h == "1"] =1
newMexico1$H_Q05hn[newMexico1$H_Q05h == "2"] =2
newMexico1$H_Q05hn[newMexico1$H_Q05h == "3"] =3
newMexico1$H_Q05hn[newMexico1$H_Q05h == "4"] =4
newMexico1$H_Q05hn[newMexico1$H_Q05h == "5"] =5

#J_Q03a

newMexico1$J_Q03an[newMexico1$J_Q03a == "N"] = NA
newMexico1$J_Q03an[newMexico1$J_Q03a == "1"] = 0
newMexico1$J_Q03an[newMexico1$J_Q03a == "2"] = 1

#J_Q03b

newMexico1$J_Q03bn[newMexico1$J_Q03b == "N"] = NA
newMexico1$J_Q03bn[newMexico1$J_Q03b == "R"] = NA
newMexico1$J_Q03bn[newMexico1$J_Q03b == "V"] = NA
newMexico1$J_Q03bn[newMexico1$J_Q03b == "1"] = 1
newMexico1$J_Q03bn[newMexico1$J_Q03b == "2"] = 2
newMexico1$J_Q03bn[newMexico1$J_Q03b == "3"] = 3
newMexico1$J_Q03bn[newMexico1$J_Q03b == "4"] = 4
newMexico1$J_Q03bn[newMexico1$J_Q03b == "5"] = 5
newMexico1$J_Q03bn[newMexico1$J_Q03b == "6"] = 6
newMexico1$J_Q03bn[newMexico1$J_Q03b == "7"] = 7
newMexico1$J_Q03bn[newMexico1$J_Q03b == "8"] = 8
newMexico1$J_Q03bn[newMexico1$J_Q03b == "9"] = 9
newMexico1$J_Q03bn[newMexico1$J_Q03b == "10"] = 10
newMexico1$J_Q03bn[newMexico1$J_Q03b == "11"] = 11
newMexico1$J_Q03bn[newMexico1$J_Q03b == "12"] = 12
newMexico1$J_Q03bn[newMexico1$J_Q03b == "13"] = 13
newMexico1$J_Q03bn[newMexico1$J_Q03b == "16"] = 16
newMexico1$J_Q03bn[newMexico1$J_Q03b == "19"] = 19

#J_Q06b

newMexico1$J_Q06bn[newMexico1$J_Q06b== "1"] = 1
newMexico1$J_Q06bn[newMexico1$J_Q06b== "2"] = 2
newMexico1$J_Q06bn[newMexico1$J_Q06b== "3"] = 3
newMexico1$J_Q06bn[newMexico1$J_Q06b== "D"] = NA
newMexico1$J_Q06bn[newMexico1$J_Q06b== "N"] = NA
newMexico1$J_Q06bn[newMexico1$J_Q06b== "R"] = NA

#J_Q07b

newMexico1$J_Q07bn[newMexico1$J_Q07b== "1"] = 1
newMexico1$J_Q07bn[newMexico1$J_Q07b== "2"] = 2
newMexico1$J_Q07bn[newMexico1$J_Q07b== "3"] = 3
newMexico1$J_Q07bn[newMexico1$J_Q07b== "D"] = NA
newMexico1$J_Q07bn[newMexico1$J_Q07b== "N"] = NA
newMexico1$J_Q07bn[newMexico1$J_Q07b== "R"] = NA


```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r warning=FALSE, message=FALSE}

#Dropping NAs in ICT work


newMexico1ICTwork1 <- drop_na(newMexico1, G_Q05an)

ICTwork1reg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + G_Q05an + G_Q05cn + G_Q05dn + G_Q05en + G_Q05gn + G_Q05hn + G_Q06n + G_Q07n + G_Q08n, newMexico1ICTwork1)

ICTreg1 <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an+ G_Q05an + G_Q05cn + G_Q05dn + G_Q05en + G_Q05gn + G_Q05hn + G_Q06n + G_Q07n + G_Q08n + H_Q05an + H_Q05cn + H_Q05dn + H_Q05en + H_Q05fn + H_Q05gn + H_Q05hn, newMexico1ICTwork1)

summary(ICTwork1reg)
summary(ICTreg1)

# Dropping NAs in ICT life

NewMexico1ICTlife <- drop_na(newMexico1,H_Q05gn)

#Regression Soft skills 

Softreg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + F_Q01bn + F_Q02bn + F_Q02cn + F_Q02dn + F_Q02en + F_Q03bn + F_Q04an + F_Q04bn + F_Q05an + F_Q05bn, newMexico1)

summary(Softreg)

#Ression Literacy work 

Literacyworkreg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + G_Q01an + G_Q02an + G_Q02bn + G_Q02cn + G_Q02dn, newMexico1)

summary(Literacyworkreg)

# Regression Literacy life

Literacylifereg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + H_Q01an + H_Q01bn + H_Q01b_Tn + H_Q01cn + H_Q01c_Tn + H_Q01dn + H_Q01en + H_Q01e_Tn + H_Q01fn + H_Q01gn + H_Q01hn + H_Q02an + H_Q02bn + H_Q02cn + H_Q02dn,  newMexico1) 


summary(Literacylifereg) 

#Regression numeracy work 

Numeracyworkreg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + G_Q03bn + G_Q03cn + G_Q03dn + G_Q03fn + G_Q03gn + G_Q03hn, newMexico1)  

summary(Numeracyworkreg) 

# Regression numeracy life

Numeracylifereg <- lm(YEARLYINCPR ~ AGE_R + GENDER_Rn + B_Q01an + H_Q03bn + H_Q03cn + H_Q03dn + H_Q03fn + H_Q03gn + H_Q03hn, newMexico1)

summary(Numeracylifereg) 

```
